// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat_participants.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addUserToChat = `-- name: AddUserToChat :exec
INSERT INTO chat_participants (chat_id, user_id)
VALUES ($1, $2)
`

type AddUserToChatParams struct {
	ChatID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) AddUserToChat(ctx context.Context, arg AddUserToChatParams) error {
	_, err := q.db.Exec(ctx, addUserToChat, arg.ChatID, arg.UserID)
	return err
}

const getChatParticipantIDs = `-- name: GetChatParticipantIDs :many

SELECT user_id FROM chat_participants
WHERE chat_id = $1
`

func (q *Queries) GetChatParticipantIDs(ctx context.Context, chatID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getChatParticipantIDs, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastRead = `-- name: UpdateLastRead :exec

UPDATE chat_participants
SET last_read_at = NOW()
WHERE chat_id = $1 AND user_id = $2
`

type UpdateLastReadParams struct {
	ChatID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) UpdateLastRead(ctx context.Context, arg UpdateLastReadParams) error {
	_, err := q.db.Exec(ctx, updateLastRead, arg.ChatID, arg.UserID)
	return err
}
