// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chats.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createChat = `-- name: CreateChat :one
INSERT INTO chats(id, name, is_group)
VALUES(
    $1,
    $2,
    $3
)
RETURNING id, name, is_group, created_at
`

type CreateChatParams struct {
	ID      uuid.UUID
	Name    *string
	IsGroup bool
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error) {
	row := q.db.QueryRow(ctx, createChat, arg.ID, arg.Name, arg.IsGroup)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsGroup,
		&i.CreatedAt,
	)
	return i, err
}

const getDirectChatBetweenUsers = `-- name: GetDirectChatBetweenUsers :one

SELECT c.id
FROM chats c
JOIN chat_participants cp1 ON c.id = cp1.chat_id
JOIN chat_participants cp2 ON c.id = cp2.chat_id
WHERE c.is_group = FALSE
  AND cp1.user_id = $1
  AND cp2.user_id = $2
LIMIT 1
`

type GetDirectChatBetweenUsersParams struct {
	UserID   uuid.UUID
	UserID_2 uuid.UUID
}

func (q *Queries) GetDirectChatBetweenUsers(ctx context.Context, arg GetDirectChatBetweenUsersParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getDirectChatBetweenUsers, arg.UserID, arg.UserID_2)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUserChats = `-- name: GetUserChats :many

SELECT
    c.id AS chat_id,
    c.name AS chat_name,
    c.is_group,
    cp.last_read_at,
    (COALESCE((SELECT content FROM messages m WHERE m.chat_id = c.id ORDER BY m.id DESC LIMIT 1), ''))::text AS last_message_content,
    (COALESCE((SELECT id FROM messages m WHERE m.chat_id = c.id ORDER BY m.id DESC LIMIT 1), '00000000-0000-0000-0000-000000000000'::uuid))::uuid AS last_message_id
FROM chats c
JOIN chat_participants cp ON c.id = cp.chat_id
WHERE cp.user_id = $1
ORDER BY last_message_id DESC
`

type GetUserChatsRow struct {
	ChatID             uuid.UUID
	ChatName           *string
	IsGroup            bool
	LastReadAt         time.Time
	LastMessageContent string
	LastMessageID      uuid.UUID
}

func (q *Queries) GetUserChats(ctx context.Context, userID uuid.UUID) ([]GetUserChatsRow, error) {
	rows, err := q.db.Query(ctx, getUserChats, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserChatsRow
	for rows.Next() {
		var i GetUserChatsRow
		if err := rows.Scan(
			&i.ChatID,
			&i.ChatName,
			&i.IsGroup,
			&i.LastReadAt,
			&i.LastMessageContent,
			&i.LastMessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
