// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChat = `-- name: CreateChat :one
INSERT INTO chats(id, name, is_group)
VALUES(
    $1,
    $2,
    $3
)
RETURNING id, name, is_group, created_at
`

type CreateChatParams struct {
	ID      pgtype.UUID
	Name    pgtype.Text
	IsGroup bool
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error) {
	row := q.db.QueryRow(ctx, createChat, arg.ID, arg.Name, arg.IsGroup)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsGroup,
		&i.CreatedAt,
	)
	return i, err
}

const getDirectChatBetweenUsers = `-- name: GetDirectChatBetweenUsers :one

SELECT cr.id
FROM chats cr
JOIN chat_rooms cr1 ON cr.id = cr1.chat_room_id
JOIN chat_rooms cr2 ON cr.id = cr2.chat_room_id
WHERE cr.is_group = FALSE
  AND cr1.user_id = $1
  AND cr2.user_id = $2
LIMIT 1
`

type GetDirectChatBetweenUsersParams struct {
	UserID   pgtype.UUID
	UserID_2 pgtype.UUID
}

func (q *Queries) GetDirectChatBetweenUsers(ctx context.Context, arg GetDirectChatBetweenUsersParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getDirectChatBetweenUsers, arg.UserID, arg.UserID_2)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
