// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one

INSERT INTO messages(id, content, sender_id, chat_id)
VALUES(
    $1,
    $2,
    $3,
    $4
)
RETURNING id, content, sender_id, chat_id, created_at, updated_at
`

type CreateMessageParams struct {
	ID       pgtype.UUID
	Content  string
	SenderID pgtype.UUID
	ChatID   pgtype.UUID
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.Content,
		arg.SenderID,
		arg.ChatID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.SenderID,
		&i.ChatID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMessagesBefore = `-- name: GetMessagesBefore :many
SELECT id, content, sender_id, chat_id, created_at, updated_at FROM messages
WHERE chat_id = $1
    AND id < $2
ORDER BY id DESC
LIMIT 50
`

type GetMessagesBeforeParams struct {
	ChatID pgtype.UUID
	ID     pgtype.UUID
}

func (q *Queries) GetMessagesBefore(ctx context.Context, arg GetMessagesBeforeParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessagesBefore, arg.ChatID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.SenderID,
			&i.ChatID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessage = `-- name: UpdateMessage :one

UPDATE messages
SET content = $1,
    updated_at = NOW() AT TIME ZONE 'UTC'
WHERE id = $2
RETURNING id, content, sender_id, chat_id, created_at, updated_at
`

type UpdateMessageParams struct {
	Content string
	ID      pgtype.UUID
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, updateMessage, arg.Content, arg.ID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.SenderID,
		&i.ChatID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
