// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Chat struct {
	ID        uuid.UUID
	Name      *string
	IsGroup   bool
	CreatedAt time.Time
}

type ChatRoom struct {
	ChatID     uuid.UUID
	UserID     uuid.UUID
	JoinedAt   time.Time
	LastReadAt time.Time
}

type EmailVerificationToken struct {
	TokenHash string
	UserID    uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
}

type Message struct {
	ID        uuid.UUID
	Content   string
	SenderID  uuid.UUID
	ChatID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type RefreshToken struct {
	TokenHash string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt pgtype.Timestamptz
}

type User struct {
	ID             uuid.UUID
	Nickname       string
	Email          string
	HashedPassword string
	IsVerified     bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
