// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Chat struct {
	ID        pgtype.UUID
	Name      pgtype.Text
	IsGroup   bool
	CreatedAt pgtype.Timestamptz
}

type ChatRoom struct {
	ChatID     pgtype.UUID
	UserID     pgtype.UUID
	JoinedAt   pgtype.Timestamptz
	LastReadAt pgtype.Timestamptz
}

type Message struct {
	ID        pgtype.UUID
	Content   string
	SenderID  pgtype.UUID
	ChatID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type User struct {
	ID             pgtype.UUID
	Nickname       string
	Email          string
	HashedPassword string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
