// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createOAuthGithubAccount = `-- name: CreateOAuthGithubAccount :one

INSERT INTO oauth_accounts (id, user_id, provider, provider_user_id, created_at)
VALUES(
    $1,
    $2,
    'github',
    $3,
    NOW() AT TIME ZONE 'UTC'
)
RETURNING id, user_id, provider, provider_user_id, created_at
`

type CreateOAuthGithubAccountParams struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	ProviderUserID string
}

func (q *Queries) CreateOAuthGithubAccount(ctx context.Context, arg CreateOAuthGithubAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, createOAuthGithubAccount, arg.ID, arg.UserID, arg.ProviderUserID)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getUserIdFromGithub = `-- name: GetUserIdFromGithub :one
SELECT user_id
FROM oauth_accounts
WHERE provider = 'github'
    AND provider_user_id = $1
`

func (q *Queries) GetUserIdFromGithub(ctx context.Context, providerUserID string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getUserIdFromGithub, providerUserID)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}
