// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addChatRoomMember = `-- name: AddChatRoomMember :exec
INSERT INTO chat_rooms (chat_id, user_id)
VALUES ($1, $2)
`

type AddChatRoomMemberParams struct {
	ChatID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) AddChatRoomMember(ctx context.Context, arg AddChatRoomMemberParams) error {
	_, err := q.db.Exec(ctx, addChatRoomMember, arg.ChatID, arg.UserID)
	return err
}
