// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id,
    token_hash,
    created_at,
    updated_at,
    user_id,
    expires_at,
    user_agent,
    ip_address,
    revoked_at
)
VALUES (
    $1,
    $2,
    NOW(),
    NOW(),
    $3,
    NOW() + INTERVAL '60 days',
    $4,
    $5,
    NULL
)
RETURNING id, token_hash, created_at, updated_at, user_id, user_agent, ip_address, expires_at, revoked_at
`

type CreateSessionParams struct {
	ID        uuid.UUID
	TokenHash string
	UserID    uuid.UUID
	UserAgent string
	IpAddress string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.TokenHash,
		arg.UserID,
		arg.UserAgent,
		arg.IpAddress,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec

DELETE FROM sessions
WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const getUserFromSession = `-- name: GetUserFromSession :one

SELECT u.id, u.nickname, u.real_name, u.birth_date, u.email, u.hashed_password, u.status, u.created_at, u.updated_at, u.deleted_at
FROM sessions s
JOIN users u ON(s.user_id = u.id)
WHERE s.token_hash = $1 AND revoked_at IS NULL AND expires_at > NOW()
`

func (q *Queries) GetUserFromSession(ctx context.Context, tokenHash string) (User, error) {
	row := q.db.QueryRow(ctx, getUserFromSession, tokenHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.RealName,
		&i.BirthDate,
		&i.Email,
		&i.HashedPassword,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserSessions = `-- name: GetUserSessions :many

SELECT id, token_hash, created_at, user_agent, ip_address
FROM sessions
WHERE user_id = $1
    AND expires_at > NOW()
    AND revoked_at IS NULL
ORDER BY created_at DESC
`

type GetUserSessionsRow struct {
	ID        uuid.UUID
	TokenHash string
	CreatedAt time.Time
	UserAgent string
	IpAddress string
}

func (q *Queries) GetUserSessions(ctx context.Context, userID uuid.UUID) ([]GetUserSessionsRow, error) {
	rows, err := q.db.Query(ctx, getUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserSessionsRow
	for rows.Next() {
		var i GetUserSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TokenHash,
			&i.CreatedAt,
			&i.UserAgent,
			&i.IpAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :exec

UPDATE sessions
SET revoked_at = NOW(),
    updated_at = NOW()
WHERE
    id = $1
    AND user_id = $2
    AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.UserID)
	return err
}

const revokeSessionByToken = `-- name: RevokeSessionByToken :exec

UPDATE sessions
SET
    revoked_at = NOW(),
    updated_at = NOW()
WHERE
    token_hash = $1
    AND revoked_at IS NULL
`

func (q *Queries) RevokeSessionByToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeSessionByToken, tokenHash)
	return err
}
