// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_relationships.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUserRelationship = `-- name: CreateUserRelationship :exec
INSERT INTO user_relationships(id, action_user_id, target_user_id, status, initial_message, created_at, updated_at)
VALUES(
    $1,
    $2,
    $3,
    $4,
    $5,
    NOW() AT TIME ZONE 'UTC',
    NOW() AT TIME ZONE 'UTC'
)
`

type CreateUserRelationshipParams struct {
	ID             uuid.UUID
	ActionUserID   uuid.UUID
	TargetUserID   uuid.UUID
	Status         string
	InitialMessage *string
}

func (q *Queries) CreateUserRelationship(ctx context.Context, arg CreateUserRelationshipParams) error {
	_, err := q.db.Exec(ctx, createUserRelationship,
		arg.ID,
		arg.ActionUserID,
		arg.TargetUserID,
		arg.Status,
		arg.InitialMessage,
	)
	return err
}

const updateUserRelationship = `-- name: UpdateUserRelationship :exec

UPDATE user_relationships
SET
    status = $1
WHERE action_user_id = $2 AND target_user_id = $3
`

type UpdateUserRelationshipParams struct {
	Status       string
	ActionUserID uuid.UUID
	TargetUserID uuid.UUID
}

func (q *Queries) UpdateUserRelationship(ctx context.Context, arg UpdateUserRelationshipParams) error {
	_, err := q.db.Exec(ctx, updateUserRelationship, arg.Status, arg.ActionUserID, arg.TargetUserID)
	return err
}
