// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const anonymizeUser = `-- name: AnonymizeUser :exec

UPDATE users
SET
    email = CONCAT('deleted_', id, '@deleted.local'),
    hashed_password = NULL,
    nickname = 'Deleted User',
    status = 'deleted',
    deleted_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND status != 'deleted'
`

func (q *Queries) AnonymizeUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, anonymizeUser, id)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users(id, nickname,  email, hashed_password)
VALUES (
    $1,
    $2,
    $3,
    $4
)
RETURNING id, nickname, email, hashed_password, status, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	ID             uuid.UUID
	Nickname       string
	Email          string
	HashedPassword *string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Nickname,
		arg.Email,
		arg.HashedPassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.Email,
		&i.HashedPassword,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one

SELECT id, nickname, email, hashed_password, status, created_at, updated_at, deleted_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.Email,
		&i.HashedPassword,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one

UPDATE users
SET email = $1,
    hashed_password = $2,
    updated_at = NOW() AT TIME ZONE 'UTC'
WHERE id = $3 AND status = 'active'
RETURNING id, nickname, email, hashed_password, status, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	Email          string
	HashedPassword *string
	ID             uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.Email, arg.HashedPassword, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.Email,
		&i.HashedPassword,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const verifyUser = `-- name: VerifyUser :exec

UPDATE users
SET status = 'active',
    updated_at = NOW() AT TIME ZONE 'UTC'
WHERE id = $1 AND status = 'unverified'
`

func (q *Queries) VerifyUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, verifyUser, id)
	return err
}
