// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification_tokens.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createVerificationToken = `-- name: CreateVerificationToken :one

INSERT INTO email_verification_tokens (
    token_hash,
    user_id
)
VALUES (
    $1,
    $2
)
RETURNING token_hash, user_id, created_at, expires_at
`

type CreateVerificationTokenParams struct {
	TokenHash string
	UserID    uuid.UUID
}

func (q *Queries) CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, createVerificationToken, arg.TokenHash, arg.UserID)
	var i EmailVerificationToken
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteVerificationTokensByUserID = `-- name: DeleteVerificationTokensByUserID :exec
DELETE FROM email_verification_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteVerificationTokensByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVerificationTokensByUserID, userID)
	return err
}

const getUserFromVerificationToken = `-- name: GetUserFromVerificationToken :one

SELECT u.id, u.nickname, u.email, u.hashed_password, u.is_verified, u.created_at, u.updated_at
FROM email_verification_tokens evt
JOIN users u ON evt.user_id = u.id
WHERE evt.token_hash = $1
  AND evt.expires_at > (NOW() AT TIME ZONE 'UTC')
`

func (q *Queries) GetUserFromVerificationToken(ctx context.Context, tokenHash string) (User, error) {
	row := q.db.QueryRow(ctx, getUserFromVerificationToken, tokenHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Nickname,
		&i.Email,
		&i.HashedPassword,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
