services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gochat-app
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_URL=${DB_URL}
      - SECRET_TOKEN=${SECRET_TOKEN}
      - SMTP_HOST=mailpit
      - SMTP_PORT=1025
    depends_on:
      - mailpit

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
